version: '3'

services:
 newt:
  container_name: newt_webapp
  build:
   context: .
   dockerfile: Dockerfile
  ports:
   - 8080:8080
  environment:
   - port=8080
  volumes:
   - .:/home/node/app
  command: >
    sh -c "npm run release-build &&
           node server.js"
