version: '3'

services:
 newt:
  container_name: newt_webapp
  build:
   context: .
  ports:
   - ${PORT}:${PORT}
  environment:
    - PORT  # pass variable to container
  volumes:
   - .:/home/node/app
  command: >
    sh -c "npm run release-build &&
           node server.js"
